function [RBR] = RSK2MAT(RSK)

% RSK2MAT - Creates a structure array from a RSK structure.
%
% Syntax: [RBR] = RSK2MAT(RSKfile)
%
% RSK2MAT converts the regular RSK structure format to the legacy .mat RBR
% structure array. The output structure (RBR) is similar to the .mat file
% generated by Ruskin but is missing some fields: comments,
% serialstarttime/serialendtime, derived channels, events, parameters and
% sample code.
%
% NOTE: Only use this function if you previously have been using the .mat
% export from Ruskin and already have scripts set up to work with this
% layout. If possible use the .rsk files directly.
% 
%
% Inputs:
%    RSK - Structure containing the logger metadata, along with the
%          added 'data' field.
%
% Outputs:
%    RBR - Structure containing the logger data and some metadata in the
%          same format as the .mat files exported by Ruskin.
%
% Example:
%   rsk = RSKopen(fname);
%   rsk = RSKreaddata(rsk);
%   RBR = RSK2MAT(rsk);
%
% Author: RBR Ltd. Ottawa ON, Canada
% email: support@rbr-global.com
% Website: www.rbr-global.com
% Last revision: 2017-08-01

if strcmpi(RSK.dbInfo(1).type, 'EasyParse');
    RSKerror('RSK2MAT is not compatible with files from Ruskin Mobile. File should be opened in Ruskin Desktop first.')
end
if size(RSK.data,2) > 1
    RSKwarning('RSK2MAT is not compatible with casts, use RSKreaddata to have one data field.')
    return
end

%% Set up metadata
[firmwareV, ~, ~]  = readfirmwarever(RSK);

RBR.name = ['RBR ' RSK.instruments.model ' ' firmwareV ' ' num2str(RSK.instruments.serialID)];

% Sample period
RBR.sampleperiod = readsamplingperiod(RSK); 

% Channels
RBR.channelnames = {RSK.channels.longName}';
RBR.channelunits = {RSK.channels.units}';
try
    RBR.channelranging = {RSK.ranging.mode}';
catch
end

% Epochs
RBR.starttime = datestr(RSK.epochs.startTime, 'dd/mm/yyyy HH:MM:SS PM');
RBR.endtime = datestr(RSK.epochs.endTime, 'dd/mm/yyyy HH:MM:SS PM');


%% Set up coefficients table
nchannels = length(RBR.channelnames);
% Salinity adds a channel but does not have calibration coefficients

hasS = any(strcmp({RSK.channels.longName}, 'Salinity'));
if hasS
    nchannels = nchannels-1;
end

if ~strcmp(RSK.dbInfo(end).type, 'EPdesktop') && ~strcmp(RSK.dbInfo(end).type, 'live')%EPdesktop & live does not have calibration table
    % Only shows first 4 coefficients (c0, c1, c2 & c3).
    RSK = RSKreadcalibrations(RSK);
    RBR.coefficients = zeros(4, nchannels);
    for ndx=1:nchannels
        channelindex = find([RSK.calibrations.channelOrder] == ndx);
        coefcell = [{RSK.calibrations(channelindex(end)).c0}; {RSK.calibrations(channelindex(end)).c1}; {RSK.calibrations(channelindex(end)).c2; RSK.calibrations(channelindex(end)).c3}];
        nocoef = cellfun('isempty', coefcell);
        coefcell(nocoef) = {NaN};
        RBR.coefficients(:,ndx) = cell2mat(coefcell);
    end
end


%% Set up data tables
RBR.sampletimes = cellstr(datestr(RSK.data.tstamp, 'yyyy-mm-dd HH:MM:ss.FFF'));
RBR.data = RSK.data.values(:,1:nchannels);


%% Save to mat file
matfile = strrep([num2str(RSK.instruments.serialID) '_' RSK.instruments.model],'.rsk','.mat');
save(matfile, 'RBR', '-v7.3');


end